#!/usr/bin/perl

print <<"EOF";
HTTP/1.0 200 OK
Content-type: text/plain

My uid: $<
My gid: $(
My euid: $>
My egid: $)
My arguments: @ARGV

HTTPi CGI env-vars:

EOF

foreach (sort keys %ENV) {
	print "$_=$ENV{$_}\n"
	if (/^QUERY_/ || /^CONTENT_/ || /^REMOTE_/ || /^REQUEST_/ ||
		/^SCRIPT_/ || /^SERVER_/ || /^HTTP_/ || /^PATH_/);
}


1;
